import type { AppSnapshot } from './types'
import { normalizeThemePalettes } from './theme'

export function createDefaultSnapshot(): AppSnapshot {
  const now = new Date().toISOString()
  return {
    version: 1,
    settings: {
      theme: 'system',
      themePalettes: normalizeThemePalettes(),
      lastTool: 'home',
      sidebarCollapsed: false,
      sidebarWidth: 300,
      pomodoroAlarmPath: '',
      displayName: 'Pandora',
      bangumiUsername: '',
      homeWallpaper: '',
      homeWallpapers: [],
      homeQuickActions: ['new-note', 'new-todo', 'pomodoro', 'music', 'collection'],
      weatherLocation: {
        name: '吉隆坡',
        country: '马来西亚',
        admin1: '',
        latitude: 3.139,
        longitude: 101.6869,
        timezone: 'Asia/Kuala_Lumpur',
      },
      weatherCache: null,
      deskCompanion: {
        enabled: false,
        scale: 1,
        dialogueMode: 'sequential',
        activeCharacterId: 'default-companion',
        characters: [{
          id: 'default-companion',
          name: '默认小伙伴',
          image: 'resources/fun/desk-companion/companion.png',
          dialogues: [
            '今天也要好好照顾自己呀。',
            '累了就休息一会儿，我会在这里。',
            '又完成了一点，已经很棒啦！',
          ],
          pressSound: 'resources/fun/desk-companion/press.mp3',
          pressSoundName: '默认按下音',
          releaseSound: 'resources/fun/desk-companion/release.mp3',
          releaseSoundName: '默认松开音',
        }],
      },
      recentTools: [],
      toolUsage: {},
      updatedAt: now,
    },
    bangumi: null,
    imageLibrary: { roots: [], collections: [], assets: [] },
    tracks: [],
    albums: [],
    folders: [],
    notes: [],
    goals: [],
    todos: [],
    pomodoro: {
      mode: 'focus',
      focusMinutes: 25,
      shortBreakMinutes: 5,
      longBreakMinutes: 15,
      sessionsBeforeLongBreak: 4,
      completedSessions: 0,
      secondsRemaining: 25 * 60,
      running: false,
      endsAt: null,
    },
    clipboardSnippets: [],
    launcherLinks: [],
  }
}
